### ISSUE TITLE
Question for PixTransform

### ISSUE THREAD

**Issue by codyshen0000** [riccardodelutio/PixTransform#2]
Hello author(s), as mentioned in your paper, the guide image and the target image are directly mapped, Does this mean we can directly transform the guide image to the target image without the source image?

**Comment by riccardodelutio** [comment]
Hi, thank you for reaching out! 
The transformation is indeed from the guide to the target (high-res), but to learn this transformation you still need a source image (low-res). What you don't need is the ground truth high-resolution target image, which is why this method is unsupervised. Hope this makes it clearer!
Riccardo
